window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

scrolling:
  # Specifying '0' will disable scrolling.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

font:
  normal:
    family: Monaspace Neon
    style: Regular
  bold:
    family: Monaspace Neon
    style: Bold
  italic:
    family: Monaspace Neon
    style: Italic
  bold_italic:
    family: Monaspace Neon
    style: Bold Italic
  size: 16.0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "0x232136"
    foreground: "0xe0def4"
  cursor:
    text: "0xe0def4"
    cursor: "0x56526e"
  vi_mode_cursor:
    text: "0xe0def4"
    cursor: "0x56526e"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0xe0def4"
    background: "0x44415a"
  normal:
    black: "0x393552"
    red: "0xeb6f92"
    green: "0x3e8fb0"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xea9a97"
    white: "0xe0def4"
  bright:
    black: "0x6e6a86"
    red: "0xeb6f92"
    green: "0x3e8fb0"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xea9a97"
    white: "0xe0def4"
  hints:
    start:
      foreground: "#908caa"
      background: "#2a273f"
    end:
      foreground: "#6e6a86"
      background: "#2a273f"

# Specifying a `duration` of `0` will disable the visual bell.
bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty’s window title.
window.dynamic_title: true
window.opacity: 0.99
cursor:
  style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

# Map the keys (British keyboard layout)
key_bindings:
  - { key: Key0, mods: Alt, chars: 'º' }
  - { key: Key1, mods: Alt, chars: '¡' }
  - { key: Key2, mods: Alt, chars: '€' }
  - { key: Key3, mods: Alt, chars: '#' }
  - { key: Key4, mods: Alt, chars: '¢' }
  - { key: Key5, mods: Alt, chars: '∞' }
  - { key: Key6, mods: Alt, chars: '§' }
  - { key: Key7, mods: Alt, chars: '¶' }
  - { key: Key8, mods: Alt, chars: '•' }
  - { key: Key9, mods: Alt, chars: 'ª' }
