env:
  TERM: xterm-256color

import:
# uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
  # - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
  # - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
  # - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

window:
  option_as_alt: OnlyLeft 
  dynamic_title: true
  opacity: 1.0
  startup_mode: Maximized
  dynamic_padding: true
  padding:
    x: 7
    y: 1
  offset:
    x: 1
    y: 0

scrolling:
  history: 100000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 16.0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

bell:
  animation: EaseOutExpo
  duration: 0

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true


cursor:
  style: Block
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

# Map the keys (British keyboard layout)
key_bindings:
  - { key: Key0, mods: Alt, chars: 'º' }
  - { key: Key1, mods: Alt, chars: '¡' }
  - { key: Key2, mods: Alt, chars: '€' }
  - { key: Key3, mods: Alt, chars: '#' }
  - { key: Key4, mods: Alt, chars: '¢' }
  - { key: Key5, mods: Alt, chars: '∞' }
  - { key: Key6, mods: Alt, chars: '§' }
  - { key: Key7, mods: Alt, chars: '¶' }
  - { key: Key8, mods: Alt, chars: '•' }
  - { key: Key9, mods: Alt, chars: 'ª' }
