import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "º"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "¢"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "¶"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "•"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "ª"
key = "Key9"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1.0
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 1
