#!/usr/bin/env sh

# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# A tiling window manager for macOS
# https://github.com/koekeishiya/yabai

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse on
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.80
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 7
yabai -m config bottom_padding 7
yabai -m config left_padding 7
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding 7
yabai -m config window_gap 7

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Stats$" manage=off

echo "yabai configuration loaded.."
